import = ["~/.config/alacritty/themes/themes/nordic.toml" ]

[window]
dimensions = {columns=100, lines=30} 
padding = {x=3, y=1}
decorations = "Full"
opacity = 0.75

[font]
normal = {family="Hack Nerd Font Mono", style="Regular"}
italic = {style = "Italic"}
bold = {style = "Bold"}
bold_italic = {style = "Bold Italic"}
size=10

